baseurl: "/IAM"
apiname: "Referentiearchitectuur voor het werken met APIs"
url: "http://localhost:4000"
# nav is t.b.v. generatie side-navigation menu.
# Een 'title' zonder path of url genereert slechts een kopje.
# 'path' vormt tezamen met de baseurl de url waarmee de 'href' wordt gevuld. 
# Indien een 'url' voorradig dan wordt daarmee de 'href' gevuld en dient het path slechts om te bepalen welke link active is.
# 'target: blank' zorgt er voor dat de link in een nieuw tabblad wordt geöpend.
nav:
  - title: Werken met APIs
    subnav:
      - title: Project
        path: /
      - title: Scope
        path: /scope  
  - title: Uitwerking 
    subnav:
      - title: Introductie
        path: /uitwerking/introductie
      - title: Use cases
        path: /uitwerking/cases
      - title: Referentiearchitectuur  
        path: /uitwerking/referentiearchitectuur
      - title: GEMMA aanpassingen  
        path: /uitwerking/gemma
      - title: Inrichtingsscenarios  
        path: /uitwerking/inrichtingsscenarios  
      - title: Terminologie  
        path: /uitwerking/terminologie
 - title: Vraag en antwoord 
    subnav:        
      - title: FAQ
        path: /faq
      - title: Contact
        path: /contact

plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

github: VNG-Realisatie/IAM

theme: jekyll-theme-cayman

remote_theme: VNG-Realisatie/jekyll-theme-vng-realisatie

project_name: /IAM

standard_family: nvt